Test project /home/user/sources/Resilient-File-Protector/build/dev
        Start   1: Crc32Tests.KnownValueForAsciiText
  1/124 Test   #1: Crc32Tests.KnownValueForAsciiText .......................................   Passed    0.01 sec
        Start   2: CryptoRegistryTests.AvailableCiphersNotEmpty
  2/124 Test   #2: CryptoRegistryTests.AvailableCiphersNotEmpty ............................   Passed    0.01 sec
        Start   3: CryptoRegistryTests.AvailableKdfsNotEmpty
  3/124 Test   #3: CryptoRegistryTests.AvailableKdfsNotEmpty ...............................   Passed    0.01 sec
        Start   4: CryptoRegistryTests.AvailableHashesNotEmpty
  4/124 Test   #4: CryptoRegistryTests.AvailableHashesNotEmpty .............................   Passed    0.01 sec
        Start   5: CryptoRegistryTests.CipherSpecLookupValid
  5/124 Test   #5: CryptoRegistryTests.CipherSpecLookupValid ...............................   Passed    0.01 sec
        Start   6: CryptoRegistryTests.CipherSpecLookupInvalid
  6/124 Test   #6: CryptoRegistryTests.CipherSpecLookupInvalid .............................   Passed    0.01 sec
        Start   7: CryptoRegistryTests.KdfSpecLookup
  7/124 Test   #7: CryptoRegistryTests.KdfSpecLookup .......................................   Passed    0.00 sec
        Start   8: CryptoRegistryTests.HashSpecLookup
  8/124 Test   #8: CryptoRegistryTests.HashSpecLookup ......................................   Passed    0.00 sec
        Start   9: CryptoRegistryTests.CipherByNameKnown
  9/124 Test   #9: CryptoRegistryTests.CipherByNameKnown ...................................   Passed    0.00 sec
        Start  10: CryptoRegistryTests.CipherByNameUnknown
 10/124 Test  #10: CryptoRegistryTests.CipherByNameUnknown .................................   Passed    0.00 sec
        Start  11: CryptoRegistryTests.KdfByName
 11/124 Test  #11: CryptoRegistryTests.KdfByName ...........................................   Passed    0.01 sec
        Start  12: CryptoRegistryTests.HashByName
 12/124 Test  #12: CryptoRegistryTests.HashByName ..........................................   Passed    0.01 sec
        Start  13: CryptoRegistryTests.BackendInfo
 13/124 Test  #13: CryptoRegistryTests.BackendInfo .........................................   Passed    0.01 sec
        Start  14: CipherTests.Aes128Gcm_TestCase1_EmptyPlaintext
 14/124 Test  #14: CipherTests.Aes128Gcm_TestCase1_EmptyPlaintext ..........................   Passed    0.01 sec
        Start  15: CipherTests.Aes128Gcm_TestCase2_16BytePlaintext
 15/124 Test  #15: CipherTests.Aes128Gcm_TestCase2_16BytePlaintext .........................   Passed    0.01 sec
        Start  16: CipherTests.Aes128Gcm_TestCase4_WithAad
 16/124 Test  #16: CipherTests.Aes128Gcm_TestCase4_WithAad .................................***Failed    0.01 sec
Running main() from ./googletest/src/gtest_main.cc
Note: Google Test filter = CipherTests.Aes128Gcm_TestCase4_WithAad
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from CipherTests
[ RUN      ] CipherTests.Aes128Gcm_TestCase4_WithAad
/home/user/sources/Resilient-File-Protector/tests/crypto/CipherTests.cpp:79: Failure
Expected equality of these values:
  toHex(r->tag)
    Which is: "da80ce830cfda02da2a218a1744f4c76"
  "5bc94fbc3221a5db94fae95ae7121a47"

[  FAILED  ] CipherTests.Aes128Gcm_TestCase4_WithAad (4 ms)
[----------] 1 test from CipherTests (4 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (4 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] CipherTests.Aes128Gcm_TestCase4_WithAad

 1 FAILED TEST

        Start  17: CipherTests.Aes256Gcm_TestCase13_EmptyPlaintext
 17/124 Test  #17: CipherTests.Aes256Gcm_TestCase13_EmptyPlaintext .........................   Passed    0.01 sec
        Start  18: CipherTests.Aes256Gcm_TestCase14_16BytePlaintext
 18/124 Test  #18: CipherTests.Aes256Gcm_TestCase14_16BytePlaintext ........................   Passed    0.01 sec
        Start  19: CipherTests.ChaCha20Poly1305_Rfc8439
 19/124 Test  #19: CipherTests.ChaCha20Poly1305_Rfc8439 ....................................   Passed    0.01 sec
        Start  20: CipherTests.DifferentKeyProducesDifferentCiphertext
 20/124 Test  #20: CipherTests.DifferentKeyProducesDifferentCiphertext .....................   Passed    0.01 sec
        Start  21: CipherTests.DifferentIvProducesDifferentCiphertext
 21/124 Test  #21: CipherTests.DifferentIvProducesDifferentCiphertext ......................   Passed    0.01 sec
        Start  22: CipherTests.DifferentAadProducesDifferentTag
 22/124 Test  #22: CipherTests.DifferentAadProducesDifferentTag ............................   Passed    0.01 sec
        Start  23: CipherTests.EmptyIvIsAutoGenerated
 23/124 Test  #23: CipherTests.EmptyIvIsAutoGenerated ......................................   Passed    0.01 sec
        Start  24: CipherTests.UnknownCipherRejected
 24/124 Test  #24: CipherTests.UnknownCipherRejected .......................................   Passed    0.00 sec
        Start  25: CipherTests.WrongKeySizeRejected
 25/124 Test  #25: CipherTests.WrongKeySizeRejected ........................................   Passed    0.00 sec
        Start  26: CipherTests.WrongIvSizeRejected
 26/124 Test  #26: CipherTests.WrongIvSizeRejected .........................................   Passed    0.00 sec
        Start  27: CipherTests.WrongTagSizeRejectedOnDecrypt
 27/124 Test  #27: CipherTests.WrongTagSizeRejectedOnDecrypt ...............................   Passed    0.00 sec
        Start  28: CipherTests.TamperedCiphertextFailsAead
 28/124 Test  #28: CipherTests.TamperedCiphertextFailsAead .................................   Passed    0.00 sec
        Start  29: CipherTests.TamperedTagFailsAead
 29/124 Test  #29: CipherTests.TamperedTagFailsAead ........................................   Passed    0.00 sec
        Start  30: CipherTests.TamperedAadFailsAead
 30/124 Test  #30: CipherTests.TamperedAadFailsAead ........................................   Passed    0.00 sec
        Start  31: CipherTests.WrongKeyFailsAeadDecryption
 31/124 Test  #31: CipherTests.WrongKeyFailsAeadDecryption .................................   Passed    0.00 sec
        Start  32: CipherTests.Aes256CbcLongerThanBlock
 32/124 Test  #32: CipherTests.Aes256CbcLongerThanBlock ....................................   Passed    0.00 sec
        Start  33: CipherTests.Aes256CtrEmptyPlaintext
 33/124 Test  #33: CipherTests.Aes256CtrEmptyPlaintext .....................................   Passed    0.00 sec
        Start  34: CipherTests.ChaCha20RoundTripNoAad
 34/124 Test  #34: CipherTests.ChaCha20RoundTripNoAad ......................................   Passed    0.01 sec
        Start  35: HashTests.Sha256KnownVectors
 35/124 Test  #35: HashTests.Sha256KnownVectors ............................................   Passed    0.00 sec
        Start  36: HashTests.Sha512KnownVectors
 36/124 Test  #36: HashTests.Sha512KnownVectors ............................................   Passed    0.00 sec
        Start  37: HashTests.Sha3_256KnownVectors
 37/124 Test  #37: HashTests.Sha3_256KnownVectors ..........................................   Passed    0.01 sec
        Start  38: HashTests.Sha3_512KnownVectors
 38/124 Test  #38: HashTests.Sha3_512KnownVectors ..........................................   Passed    0.01 sec
        Start  39: HashTests.Blake2bKnownVectors
 39/124 Test  #39: HashTests.Blake2bKnownVectors ...........................................   Passed    0.01 sec
        Start  40: HashTests.DigestSizesMatchRegistry
 40/124 Test  #40: HashTests.DigestSizesMatchRegistry ......................................   Passed    0.01 sec
        Start  41: HashTests.UnknownHashReturnsError
 41/124 Test  #41: HashTests.UnknownHashReturnsError .......................................   Passed    0.01 sec
        Start  42: HashTests.HmacSha256_Rfc4231_TestCase1
 42/124 Test  #42: HashTests.HmacSha256_Rfc4231_TestCase1 ..................................   Passed    0.01 sec
        Start  43: HashTests.HmacSha256_Rfc4231_TestCase2
 43/124 Test  #43: HashTests.HmacSha256_Rfc4231_TestCase2 ..................................   Passed    0.01 sec
        Start  44: HashTests.HmacSha256_Rfc4231_TestCase3
 44/124 Test  #44: HashTests.HmacSha256_Rfc4231_TestCase3 ..................................   Passed    0.01 sec
        Start  45: HashTests.HmacSha512_Rfc4231_TestCase1
 45/124 Test  #45: HashTests.HmacSha512_Rfc4231_TestCase1 ..................................   Passed    0.01 sec
        Start  46: HashTests.HmacSha512_Rfc4231_TestCase2
 46/124 Test  #46: HashTests.HmacSha512_Rfc4231_TestCase2 ..................................   Passed    0.01 sec
        Start  47: HashTests.HmacWorksWithAllHashes
 47/124 Test  #47: HashTests.HmacWorksWithAllHashes ........................................   Passed    0.01 sec
        Start  48: HashTests.HmacEmptyKeyAndData
 48/124 Test  #48: HashTests.HmacEmptyKeyAndData ...........................................***Failed    0.01 sec
Running main() from ./googletest/src/gtest_main.cc
Note: Google Test filter = HashTests.HmacEmptyKeyAndData
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from HashTests
[ RUN      ] HashTests.HmacEmptyKeyAndData
/home/user/sources/Resilient-File-Protector/tests/crypto/HashTests.cpp:164: Failure
Value of: m
  Actual: false
Expected: true

[  FAILED  ] HashTests.HmacEmptyKeyAndData (2 ms)
[----------] 1 test from HashTests (2 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (2 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] HashTests.HmacEmptyKeyAndData

 1 FAILED TEST

        Start  49: HashTests.DifferentInputsDifferentDigests
 49/124 Test  #49: HashTests.DifferentInputsDifferentDigests ...............................   Passed    0.01 sec
        Start  50: HashTests.HmacDifferentKeyDifferentTag
 50/124 Test  #50: HashTests.HmacDifferentKeyDifferentTag ..................................   Passed    0.01 sec
        Start  51: KdfTests.Pbkdf2Sha256_Iter1
 51/124 Test  #51: KdfTests.Pbkdf2Sha256_Iter1 .............................................   Passed    0.01 sec
        Start  52: KdfTests.Pbkdf2Sha256_Iter2
 52/124 Test  #52: KdfTests.Pbkdf2Sha256_Iter2 .............................................   Passed    0.01 sec
        Start  53: KdfTests.Pbkdf2Sha256_Iter4096
 53/124 Test  #53: KdfTests.Pbkdf2Sha256_Iter4096 ..........................................   Passed    0.01 sec
        Start  54: KdfTests.Pbkdf2Sha512_Iter1
 54/124 Test  #54: KdfTests.Pbkdf2Sha512_Iter1 .............................................   Passed    0.01 sec
        Start  55: KdfTests.Pbkdf2Sha512_Iter2
 55/124 Test  #55: KdfTests.Pbkdf2Sha512_Iter2 .............................................   Passed    0.01 sec
        Start  56: KdfTests.Pbkdf2Sha512_Iter4096
 56/124 Test  #56: KdfTests.Pbkdf2Sha512_Iter4096 ..........................................   Passed    0.02 sec
        Start  57: KdfTests.Pbkdf2OutputLengthRespected
 57/124 Test  #57: KdfTests.Pbkdf2OutputLengthRespected ....................................   Passed    0.01 sec
        Start  58: KdfTests.ScryptIsDeterministic
 58/124 Test  #58: KdfTests.ScryptIsDeterministic ..........................................   Passed    0.15 sec
        Start  59: KdfTests.ScryptDifferentSalt
 59/124 Test  #59: KdfTests.ScryptDifferentSalt ............................................   Passed    0.19 sec
        Start  60: KdfTests.ScryptDifferentPassword
 60/124 Test  #60: KdfTests.ScryptDifferentPassword ........................................   Passed    0.13 sec
        Start  61: KdfTests.Argon2idNotImplemented
 61/124 Test  #61: KdfTests.Argon2idNotImplemented .........................................   Passed    0.00 sec
        Start  62: KdfTests.EmptySaltRejected
 62/124 Test  #62: KdfTests.EmptySaltRejected ..............................................   Passed    0.00 sec
        Start  63: KdfTests.ZeroKeyLengthRejected
 63/124 Test  #63: KdfTests.ZeroKeyLengthRejected ..........................................   Passed    0.00 sec
        Start  64: KdfTests.UnknownKdfRejected
 64/124 Test  #64: KdfTests.UnknownKdfRejected .............................................   Passed    0.01 sec
        Start  65: KdfTests.EmptyPasswordStillWorks
 65/124 Test  #65: KdfTests.EmptyPasswordStillWorks ........................................   Passed    0.01 sec
        Start  66: KdfTests.GenerateSalt
 66/124 Test  #66: KdfTests.GenerateSalt ...................................................   Passed    0.01 sec
        Start  67: RandomTests.BytesSizeRespected
 67/124 Test  #67: RandomTests.BytesSizeRespected ..........................................   Passed    0.01 sec
        Start  68: RandomTests.ConsecutiveCallsDiffer
 68/124 Test  #68: RandomTests.ConsecutiveCallsDiffer ......................................   Passed    0.01 sec
        Start  69: RandomTests.FillModifiesBuffer
 69/124 Test  #69: RandomTests.FillModifiesBuffer ..........................................   Passed    0.01 sec
        Start  70: RandomTests.FillEmptyIsSafe
 70/124 Test  #70: RandomTests.FillEmptyIsSafe .............................................   Passed    0.01 sec
        Start  71: SecureMemoryTests.WipeZeroesBuffer
 71/124 Test  #71: SecureMemoryTests.WipeZeroesBuffer ......................................   Passed    0.01 sec
        Start  72: SecureMemoryTests.WipeEmptyIsSafe
 72/124 Test  #72: SecureMemoryTests.WipeEmptyIsSafe .......................................   Passed    0.01 sec
        Start  73: SecureMemoryTests.WipeSingleByte
 73/124 Test  #73: SecureMemoryTests.WipeSingleByte ........................................   Passed    0.01 sec
        Start  74: SecureMemoryTests.ConstantTimeEqualsSame
 74/124 Test  #74: SecureMemoryTests.ConstantTimeEqualsSame ................................   Passed    0.01 sec
        Start  75: SecureMemoryTests.ConstantTimeEqualsDifferent
 75/124 Test  #75: SecureMemoryTests.ConstantTimeEqualsDifferent ...........................   Passed    0.01 sec
        Start  76: SecureMemoryTests.ConstantTimeEqualsDifferentSizes
 76/124 Test  #76: SecureMemoryTests.ConstantTimeEqualsDifferentSizes ......................   Passed    0.01 sec
        Start  77: SecureMemoryTests.ConstantTimeEqualsEmpty
 77/124 Test  #77: SecureMemoryTests.ConstantTimeEqualsEmpty ...............................   Passed    0.01 sec
        Start  78: SecureMemoryTests.ConstantTimeEqualsEmptyVsNonEmpty
 78/124 Test  #78: SecureMemoryTests.ConstantTimeEqualsEmptyVsNonEmpty .....................   Passed    0.01 sec
        Start  79: SecureMemoryTests.ConstantTimeEqualsHighBitDifference
 79/124 Test  #79: SecureMemoryTests.ConstantTimeEqualsHighBitDifference ...................   Passed    0.01 sec
        Start  80: EncodingTests.Base64EncodeRfc4648Vectors
 80/124 Test  #80: EncodingTests.Base64EncodeRfc4648Vectors ................................   Passed    0.01 sec
        Start  81: EncodingTests.Base64DecodeRfc4648Vectors
 81/124 Test  #81: EncodingTests.Base64DecodeRfc4648Vectors ................................   Passed    0.01 sec
        Start  82: EncodingTests.Base64RoundTrip
 82/124 Test  #82: EncodingTests.Base64RoundTrip ...........................................   Passed    0.01 sec
        Start  83: EncodingTests.Base64DecodeInvalidReturnsEmpty
 83/124 Test  #83: EncodingTests.Base64DecodeInvalidReturnsEmpty ...........................   Passed    0.01 sec
        Start  84: EncodingTests.HexEncodeKnown
 84/124 Test  #84: EncodingTests.HexEncodeKnown ............................................   Passed    0.01 sec
        Start  85: EncodingTests.HexDecodeKnown
 85/124 Test  #85: EncodingTests.HexDecodeKnown ............................................   Passed    0.01 sec
        Start  86: EncodingTests.HexRoundTrip
 86/124 Test  #86: EncodingTests.HexRoundTrip ..............................................   Passed    0.01 sec
        Start  87: EncodingTests.HexDecodeOddLengthReturnsEmpty
 87/124 Test  #87: EncodingTests.HexDecodeOddLengthReturnsEmpty ............................   Passed    0.01 sec
        Start  88: EncodingTests.HexDecodeInvalidCharReturnsEmpty
 88/124 Test  #88: EncodingTests.HexDecodeInvalidCharReturnsEmpty ..........................   Passed    0.01 sec
        Start  89: StegoParamsTests.DefaultValues
 89/124 Test  #89: StegoParamsTests.DefaultValues ..........................................   Passed    0.01 sec
        Start  90: StegoDispersionTests.SolidImageDispersionZero
 90/124 Test  #90: StegoDispersionTests.SolidImageDispersionZero ...........................   Passed    0.01 sec
        Start  91: StegoDispersionTests.StableDispersionAfterBitZeroing
 91/124 Test  #91: StegoDispersionTests.StableDispersionAfterBitZeroing ....................   Passed    0.01 sec
        Start  92: StegoDispersionTests.WindowSizeAffectsDispersion
 92/124 Test  #92: StegoDispersionTests.WindowSizeAffectsDispersion ........................   Passed    0.01 sec
        Start  93: StegoRoundTripTests.EmbedsAndExtractsTextSequentially
 93/124 Test  #93: StegoRoundTripTests.EmbedsAndExtractsTextSequentially ...................   Passed    0.01 sec
        Start  94: StegoRoundTripTests.EmbedsAndExtractsTextWithSeededDistribution
 94/124 Test  #94: StegoRoundTripTests.EmbedsAndExtractsTextWithSeededDistribution .........   Passed    0.01 sec
        Start  95: StegoRoundTripTests.ReportsCapacityError
 95/124 Test  #95: StegoRoundTripTests.ReportsCapacityError ................................   Passed    0.01 sec
        Start  96: StegoRoundTripTests.CalculatesCapacity
 96/124 Test  #96: StegoRoundTripTests.CalculatesCapacity ..................................   Passed    0.01 sec
        Start  97: SmartSelectionTests.CapacitySmartFiltersByThreshold
 97/124 Test  #97: SmartSelectionTests.CapacitySmartFiltersByThreshold .....................   Passed    0.01 sec
        Start  98: SmartSelectionTests.RoundTripWithSmartSelection
 98/124 Test  #98: SmartSelectionTests.RoundTripWithSmartSelection .........................   Passed    0.01 sec
        Start  99: SmartSelectionTests.BuildSlotsSmartRespectsThreshold
 99/124 Test  #99: SmartSelectionTests.BuildSlotsSmartRespectsThreshold ....................   Passed    0.01 sec
        Start 100: ImageBufferTests.IsValidDetectsInvalidState
100/124 Test #100: ImageBufferTests.IsValidDetectsInvalidState .............................   Passed    0.01 sec
        Start 101: ImageBufferTests.ByteSizeCalculation
101/124 Test #101: ImageBufferTests.ByteSizeCalculation ....................................   Passed    0.01 sec
        Start 102: CapacityTests.UniformModeWithDifferentBitsPerChannel
102/124 Test #102: CapacityTests.UniformModeWithDifferentBitsPerChannel ....................   Passed    0.01 sec
        Start 103: CapacityTests.DispersionModeVariesWithThreshold
103/124 Test #103: CapacityTests.DispersionModeVariesWithThreshold .........................   Passed    0.01 sec
        Start 104: CapacityTests.InvalidParamsReturnZero
104/124 Test #104: CapacityTests.InvalidParamsReturnZero ...................................   Passed    0.01 sec
        Start 105: StegoSlotsTests.ChannelEnabled
105/124 Test #105: StegoSlotsTests.ChannelEnabled ..........................................   Passed    0.01 sec
        Start 106: StegoSlotsTests.AvailableSlotCountHandlesEdgeCases
106/124 Test #106: StegoSlotsTests.AvailableSlotCountHandlesEdgeCases ......................   Passed    0.01 sec
        Start 107: StegoSlotsTests.BuildSlotsSuccessWithShuffle
107/124 Test #107: StegoSlotsTests.BuildSlotsSuccessWithShuffle ............................   Passed    0.01 sec
        Start 108: StegoSlotsTests.BuildSlotsErrors
108/124 Test #108: StegoSlotsTests.BuildSlotsErrors ........................................   Passed    0.01 sec
        Start 109: StegoEncoderTests.EmbedBytesErrors
109/124 Test #109: StegoEncoderTests.EmbedBytesErrors ......................................   Passed    0.01 sec
        Start 110: StegoEncoderTests.EmbedTextErrors
110/124 Test #110: StegoEncoderTests.EmbedTextErrors .......................................   Passed    0.01 sec
        Start 111: StegoDecoderTests.ExtractBytesEdgeCases
111/124 Test #111: StegoDecoderTests.ExtractBytesEdgeCases .................................   Passed    0.01 sec
        Start 112: DispersionCalculatorTests.ConstructorThrowsOnInvalidImage
112/124 Test #112: DispersionCalculatorTests.ConstructorThrowsOnInvalidImage ...............   Passed    0.01 sec
        Start 113: DispersionCalculatorTests.ConstructorThrowsOnInvalidBitsPerChannel
113/124 Test #113: DispersionCalculatorTests.ConstructorThrowsOnInvalidBitsPerChannel ......   Passed    0.01 sec
        Start 114: DispersionCalculatorTests.WindowSizeIsCorrected
114/124 Test #114: DispersionCalculatorTests.WindowSizeIsCorrected .........................   Passed    0.01 sec
        Start 115: DispersionCalculatorTests.PerChannelMetricWorks
115/124 Test #115: DispersionCalculatorTests.PerChannelMetricWorks .........................   Passed    0.01 sec
        Start 116: DispersionCalculatorTests.SumMetricWorks
116/124 Test #116: DispersionCalculatorTests.SumMetricWorks ................................   Passed    0.01 sec
        Start 117: DispersionCalculatorTests.InvalidChannelIndexReturnsZero
117/124 Test #117: DispersionCalculatorTests.InvalidChannelIndexReturnsZero ................   Passed    0.01 sec
        Start 118: DispersionCalculatorTests.CacheBehavior
118/124 Test #118: DispersionCalculatorTests.CacheBehavior .................................   Passed    0.01 sec
        Start 119: DispersionCalculatorTests.LuminanceMetricWithAlphaIgnored
119/124 Test #119: DispersionCalculatorTests.LuminanceMetricWithAlphaIgnored ...............   Passed    0.01 sec
        Start 120: AllCiphers/CipherRoundTrip.EncryptDecrypt/4-byte object <00-00 00-00>
120/124 Test #120: AllCiphers/CipherRoundTrip.EncryptDecrypt/4-byte object <00-00 00-00> ...   Passed    0.01 sec
        Start 121: AllCiphers/CipherRoundTrip.EncryptDecrypt/4-byte object <01-00 00-00>
121/124 Test #121: AllCiphers/CipherRoundTrip.EncryptDecrypt/4-byte object <01-00 00-00> ...   Passed    0.01 sec
        Start 122: AllCiphers/CipherRoundTrip.EncryptDecrypt/4-byte object <02-00 00-00>
122/124 Test #122: AllCiphers/CipherRoundTrip.EncryptDecrypt/4-byte object <02-00 00-00> ...   Passed    0.01 sec
        Start 123: AllCiphers/CipherRoundTrip.EncryptDecrypt/4-byte object <03-00 00-00>
123/124 Test #123: AllCiphers/CipherRoundTrip.EncryptDecrypt/4-byte object <03-00 00-00> ...   Passed    0.01 sec
        Start 124: AllCiphers/CipherRoundTrip.EncryptDecrypt/4-byte object <04-00 00-00>
124/124 Test #124: AllCiphers/CipherRoundTrip.EncryptDecrypt/4-byte object <04-00 00-00> ...   Passed    0.01 sec

98% tests passed, 2 tests failed out of 124

Total Test time (real) =   1.51 sec

The following tests FAILED:
	 16 - CipherTests.Aes128Gcm_TestCase4_WithAad (Failed)
	 48 - HashTests.HmacEmptyKeyAndData (Failed)
