#include "rfp/payload/PayloadCrypto.h"

#include "rfp/core/Error.h"
#include "rfp/crypto/Cipher.h"
#include "rfp/crypto/CryptoRegistry.h"
#include "rfp/crypto/Kdf.h"
#include "rfp/crypto/Random.h"
#include "rfp/crypto/SecureMemory.h"

#include <cstring>

namespace rfp::payload {

namespace {

using rfp::core::Byte;
using rfp::core::ByteBuffer;
using rfp::core::Error;
using rfp::core::ErrorCode;
using rfp::core::Result;

constexpr std::size_t kHeaderSize = 16;
constexpr std::size_t kSaltSize   = 16;
constexpr std::uint8_t kVersion   = 1;
constexpr char kMagic[4] = {'R', 'F', 'P', '1'};

void putU32BE(ByteBuffer& out, std::uint32_t v) {
    out.push_back(static_cast<Byte>((v >> 24) & 0xFF));
    out.push_back(static_cast<Byte>((v >> 16) & 0xFF));
    out.push_back(static_cast<Byte>((v >>  8) & 0xFF));
    out.push_back(static_cast<Byte>( v        & 0xFF));
}

std::uint32_t getU32BE(const Byte* p) noexcept {
    return (static_cast<std::uint32_t>(p[0]) << 24) |
           (static_cast<std::uint32_t>(p[1]) << 16) |
           (static_cast<std::uint32_t>(p[2]) <<  8) |
           static_cast<std::uint32_t>(p[3]);
}

} // namespace

Result<ByteBuffer> encrypt(std::span<const Byte> plaintext,
                           const EncryptParams& params)
{
    if (params.password.empty())
        return Error{ErrorCode::InvalidArgument, "Password must not be empty"};

    const auto cipherSpec = rfp::crypto::CryptoRegistry::cipherSpec(params.cipher);
    if (!cipherSpec)
        return Error{ErrorCode::InvalidArgument, "Unknown cipher"};

    const auto kdfSpec = rfp::crypto::CryptoRegistry::kdfSpec(params.kdf);
    if (!kdfSpec)
        return Error{ErrorCode::InvalidArgument, "Unknown KDF"};

    // 1. Salt
    auto saltResult = rfp::crypto::Random::bytes(kSaltSize);
    if (!saltResult) return saltResult.error();
    ByteBuffer salt = std::move(saltResult.value());

    // 2. Derive key
    rfp::crypto::KdfParams kdfParams;
    kdfParams.salt        = salt;
    kdfParams.iterations  = params.iterations;
    kdfParams.parallelism = 1;

    auto keyResult = rfp::crypto::Kdf::deriveKey(
        params.kdf, params.password, kdfParams, cipherSpec->keySize);
    if (!keyResult) return keyResult.error();
    ByteBuffer key = std::move(keyResult.value());

    // 3. Encrypt (IV is auto-generated by Cipher)
    rfp::crypto::CipherParams cp;
    cp.key = key;

    auto encResult = rfp::crypto::Cipher::encrypt(params.cipher, cp, plaintext);
    rfp::crypto::secureWipe(key);
    if (!encResult) return encResult.error();

    auto& enc = encResult.value();

    // 4. Serialize
    ByteBuffer out;
    out.reserve(kHeaderSize + salt.size() + enc.iv.size() +
                enc.ciphertext.size() + enc.tag.size());

    out.insert(out.end(), kMagic, kMagic + 4);
    out.push_back(kVersion);
    out.push_back(static_cast<Byte>(params.cipher));
    out.push_back(static_cast<Byte>(params.kdf));
    out.push_back(0);                                     // flags
    putU32BE(out, params.iterations);
    out.push_back(static_cast<Byte>(salt.size()));
    out.push_back(static_cast<Byte>(enc.iv.size()));
    out.push_back(0);
    out.push_back(0);

    out.insert(out.end(), salt.begin(),         salt.end());
    out.insert(out.end(), enc.iv.begin(),       enc.iv.end());
    out.insert(out.end(), enc.ciphertext.begin(), enc.ciphertext.end());
    out.insert(out.end(), enc.tag.begin(),      enc.tag.end());

    return out;
}

Result<ByteBuffer> decrypt(std::span<const Byte> encrypted,
                           const DecryptParams& params)
{
    if (params.password.empty())
        return Error{ErrorCode::InvalidArgument, "Password must not be empty"};

    if (encrypted.size() < kHeaderSize)
        return Error{ErrorCode::DecodeError, "Encrypted payload too short"};

    const Byte* p = encrypted.data();

    if (std::memcmp(p, kMagic, 4) != 0)
        return Error{ErrorCode::DecodeError,
                     "Invalid magic — not an RFP1 payload (wrong password?)"};

    if (p[4] != kVersion)
        return Error{ErrorCode::DecodeError, "Unsupported payload version"};

    const auto cipherId = static_cast<rfp::crypto::CipherId>(p[5]);
    const auto kdfId    = static_cast<rfp::crypto::KdfId>(p[6]);
    const std::uint32_t iterations = getU32BE(p + 8);
    const std::size_t saltLen = p[12];
    const std::size_t ivLen   = p[13];

    const auto cipherSpec = rfp::crypto::CryptoRegistry::cipherSpec(cipherId);
    if (!cipherSpec)
        return Error{ErrorCode::DecodeError, "Unknown cipher in payload"};

    if (ivLen != cipherSpec->ivSize)
        return Error{ErrorCode::DecodeError, "IV size mismatch"};

    const std::size_t minSize =
        kHeaderSize + saltLen + ivLen + cipherSpec->tagSize;
    if (encrypted.size() < minSize)
        return Error{ErrorCode::DecodeError, "Truncated payload"};

    const std::size_t saltOff = kHeaderSize;
    const std::size_t ivOff   = saltOff + saltLen;
    const std::size_t ctOff   = ivOff   + ivLen;
    const std::size_t ctEnd   = encrypted.size() - cipherSpec->tagSize;

    ByteBuffer salt(p + saltOff, p + saltOff + saltLen);
    ByteBuffer iv  (p + ivOff,   p + ivOff   + ivLen);
    ByteBuffer ct  (p + ctOff,   p + ctEnd);

    ByteBuffer tag;
    if (cipherSpec->tagSize > 0)
        tag.assign(p + ctEnd, p + encrypted.size());

    // Derive key
    rfp::crypto::KdfParams kdfParams;
    kdfParams.salt        = salt;
    kdfParams.iterations  = iterations;
    kdfParams.parallelism = 1;

    auto keyResult = rfp::crypto::Kdf::deriveKey(
        kdfId, params.password, kdfParams, cipherSpec->keySize);
    if (!keyResult) return keyResult.error();
    ByteBuffer key = std::move(keyResult.value());

    rfp::crypto::CipherParams cp;
    cp.key = key;
    cp.iv  = iv;
    cp.tag = tag;

    auto decResult = rfp::crypto::Cipher::decrypt(cipherId, cp, ct);
    rfp::crypto::secureWipe(key);
    return decResult;
}

bool isPayload(std::span<const Byte> data) noexcept
{
    return data.size() >= kHeaderSize &&
           std::memcmp(data.data(), kMagic, 4) == 0 &&
           data[4] == kVersion;
}

} // namespace rfp::payload
